/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_open_lib_sndfile_Connector */

#ifndef _Included_com_open_lib_sndfile_Connector
#define _Included_com_open_lib_sndfile_Connector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_open_lib_sndfile_Connector
 * Method:    callLibsndjniInvert
 * Signature: (Ljava/lang/String;Ljava/lang/String;F)I
 */
JNIEXPORT jint JNICALL Java_com_open_lib_sndfile_Connector_callLibsndjniInvert
  (JNIEnv *, jobject, jstring, jstring, jfloat);

#ifdef __cplusplus
}
#endif
#endif
